### ISSUE TITLE
新增行数据，然后删除，会生成空数据，导致读取失败。

### ISSUE THREAD

**Issue by nanwentian** [huangkumao/ConfigTools#1]
解决办法：
CfgHelper.GenCfg 的方法里，在往sw里写数据之前，先用一个 stringbuilder 缓存一下，把不合法的数据 continue掉。
只把合法的数据往sw里面写。

**Comment by huangkumao** [comment]
理论上不合法的数据 在导出的时候报错是正常的 能尽早报出问题, 当然现在工具里遇到没有填值的情况 没有给默认值 也没有报错 可能是有点问题
